### ISSUE TITLE
about add tonhub wallets-list version

### ISSUE THREAD

**Issue by LeoWangJ** [ton-blockchain/wallets-list#15]
I'm using`@tonconnect/sdk@2.1.0`  default walletsListSource (add tonhub wallets-list version ) occur this error
previous version (not add tonhub) is working well 

<img width="530" alt="截圖 2023-03-22 下午12 26 11" src="https://user-images.githubusercontent.com/17901443/226802050-3905dbf7-b0f1-473c-a66b-7c73e6b83fd4.png">

**Comment by gohryt** [comment]
same as LeoWangJ

**Comment by gohryt** [comment]
there is no 'universal_url' for Tonhub but validation in tonconnect requires it
```
if (sseBridge) {
    if (
        !('url' in sseBridge) ||
        !(sseBridge as { url: string }).url ||
        !(value as { universal_url: string }).universal_url
    ) {
        return false;
    }
} 
```

**Comment by EmelyanenkoK** [comment]
Thanks, we've reverted the last changes for now. Will merge Tonhub soon with correct config.
